"""Original research/design prose for the 0xF77 report, 2026-10-07."""

SOURCES = [
('S01','ANSI FORTRAN 77 full language, WG5 archive','https://wg5-fortran.org/ARCHIVE/Fortran77.html','Sections 12-13; Appendix C distinguishes compatibility Hollerith from the standard language.'),
('S02','J3/23-007r1, Fortran 2023 committee draft','https://j3-fortran.org/doc/year/23/23-007r1.pdf','Annex B: deleted and obsolescent features. A public draft, not the purchased ISO publication.'),
('S03','GNU Fortran: dialect options','https://gcc.gnu.org/onlinedocs/gfortran/Fortran-Dialect-Options.html','Legacy mode, source width, D lines and DEC compatibility switches.'),
('S04','Sun/Oracle F77: standard fixed format','https://docs.oracle.com/cd/E19957-01/805-4939/z40007331fe6/index.html','Columns, continuation and padding.'),
('S05','Sun/Oracle F77: internal files','https://docs.oracle.com/cd/E19957-01/805-4939/6j4m0vnc2/index.html','Character objects as records; marks internal direct access as an extension.'),
('S06','Sun/Oracle F77: format identifier','https://docs.oracle.com/cd/E19957-01/805-4939/z400073d10bb9/index.html','Explicitly identifies integer-array formats as nonstandard.'),
('S07','IBM XL: interaction of I/O lists and formats','https://www.ibm.com/docs/en/xl-fortran-linux/16.1.0?topic=formatting-interaction-inputoutput-lists-format-specifications','Format control and list consumption.'),
('S08','Sun/Oracle F77: positional editing','https://docs.oracle.com/cd/E19957-01/805-4939/z40007439682/index.html','T/TL/TR; distinguish vendor terminal/seek restrictions from language semantics.'),
('S09','Sun/Oracle F77: blank editing','https://docs.oracle.com/cd/E19957-01/805-4939/z40007438673/index.html','BN and BZ versus vendor B.'),
('S10','Sun/Oracle F77: scale factor','https://docs.oracle.com/cd/E19957-01/805-4939/z4000743a6e2/index.html','P affects conversion, with descriptor-dependent behavior.'),
('S11','IBM XL: H editing','https://www.ibm.com/docs/en/xl-fortran-aix/16.1.0?topic=descriptors-h-editing','Output literal syntax; input use prohibited.'),
('S12','GNU Fortran: Hollerith constants','https://gcc.gnu.org/onlinedocs/gfortran/Hollerith-constants-support.html','Numeric storage of literal character bytes.'),
('S13','Sun/Oracle F77: character editing','https://docs.oracle.com/cd/E19957-01/805-4939/z40007438b4d/index.html','Hollerith A editing into noncharacter objects.'),
('S14','GNU Fortran: sequential unformatted file format','https://gcc.gnu.org/onlinedocs/gfortran/File-format-of-unformatted-sequential-files.html','Record markers, subrecords and representation dependence.'),
('S15','Sun/Oracle F77: BACKSPACE','https://docs.oracle.com/cd/E19957-01/805-4939/6j4m0vn7j/index.html','Record positioning; direct-access restrictions.'),
('S16','Sun/Oracle F77: direct access','https://docs.oracle.com/cd/E19957-01/805-4939/6j4m0vnc1/index.html','Fixed record topology and REC selection.'),
('S17','Sun/Oracle F77: BLOCK DATA','https://docs.oracle.com/cd/E19957-01/805-4939/6j4m0vn7l/index.html','Named-common initialization and restrictions.'),
('S18','GNU g77 3.4.6: block data and libraries','https://gcc.gnu.org/onlinedocs/gcc-3.4.6/g77/Block-Data-and-Libraries.html','Historical EXTERNAL technique. This is g77 documentation, not proof about gfortran.'),
('S19','GNU Fortran: code generation options','https://gcc.gnu.org/onlinedocs/gfortran/Code-Gen-Options.html','COMMON padding, static allocation options and ABI switches.'),
('S20','Sun/Oracle F77: COMMON','https://docs.oracle.com/cd/E19957-01/805-4939/6j4m0vn7v/index.html','Storage sharing across program units.'),
('S21','Sun/Oracle F77: SAVE','https://docs.oracle.com/cd/E19957-01/805-4939/6j4m0vnb7/index.html','Retention and the distinction between language guarantees and Sun defaults.'),
('S22','Sun/Oracle F77: DATA','https://docs.oracle.com/cd/E19957-01/805-4939/6j4m0vn85/index.html','Initialization and implied DO lists.'),
('S23','Sun/Oracle F77: ENTRY','https://docs.oracle.com/cd/E19957-01/805-4939/6j4m0vn99/index.html','Multiple procedure entry points and argument lists.'),
('S24','Sun/Oracle F77: assumed-size arrays','https://docs.oracle.com/cd/E19957-01/805-4939/z40007367227/index.html','Array storage sequences and dummy declarations.'),
('S25','GNU Fortran: argument passing conventions','https://gcc.gnu.org/onlinedocs/gfortran/Argument-passing-conventions.html','ABI conventions, hidden arguments and temporaries.'),
('S26','LLVM Flang: aliasing in Fortran','https://flang.llvm.org/docs/Aliasing.html','The reference-passing intuition does not waive aliasing restrictions.'),
('S27','Sun/Oracle F77: statement functions','https://docs.oracle.com/cd/E19957-01/805-4939/6j4m0vnb9/index.html','Expression-local procedures and scope.'),
('S28','GNU Fortran: variable FORMAT expressions','https://gcc.gnu.org/onlinedocs/gfortran/Variable-FORMAT-expressions.html','Documents the unsupported extension and a replacement.'),
('S29','GNU Fortran: ENCODE and DECODE','https://gcc.gnu.org/onlinedocs/gfortran/ENCODE-and-DECODE-statements.html','Not implemented; character internal files are the replacement.'),
('S30','GNU Fortran: extended I/O specifiers','https://gcc.gnu.org/onlinedocs/gfortran/Extended-I_002fO-specifiers.html','DEC carriage-control compatibility is opt-in.'),
('S31','GNU ld: OVERLAY description','https://sourceware.org/binutils/docs/ld/Overlay-Description.html','Load/run addresses and the need for an overlay manager.'),
('S32','Sun/Oracle F77: list-directed I/O','https://docs.oracle.com/cd/E19957-01/805-4939/6j4m0vnc5/index.html','Null fields, repeated values and slash termination.'),
('S33','GNU Fortran: Cray pointers','https://gcc.gnu.org/onlinedocs/gfortran/Cray-pointers.html','Nonstandard address/pointee pairs and aliasing limitations.'),
('S34','GNU Fortran: TRANSFER','https://gcc.gnu.org/onlinedocs/gfortran/TRANSFER.html','Explicit bit-pattern reinterpretation in Fortran 90 and later.'),
('S35','Bratley and Millo, Computer Recreations: Self-Reproducing Programs (1972)','https://fab.cba.mit.edu/classes/MAS.865/topics/self_replication/Bratley.pdf','Software: Practice and Experience 2, 397-400; FORTRAN card-image reproduction is prior art.'),
('S36','Nicholas Carlini, IOCCC 2020 printf machine','https://www.ioccc.org/2020/carlini/index.html','Author explanation of computation in formatted output. No first-format-computation claim is made here.'),
('S37','GNU Fortran: evaluation of logical expressions','https://gcc.gnu.org/onlinedocs/gfortran/Evaluation-of-logical-expressions.html','Evaluation may omit calls; no portable short-circuit side-effect machine.'),
('S38','IBM 1401 Fortran Specifications and Operating Procedures, April 1965','https://ibm-1401.info/C24-1455-2_Fortran_Specifications_and_Operating_Procedures_Apr65.pdf','H-conversion, printed page 17: input replaces literal characters used by subsequent output; primary manual in an archival collection.'),
]

# Every card answers intent, unusual capability, provenance, current GNU
# support, modern-language status, composition, and architectural usefulness.
FEATURES = [
('01','Fixed-form source geometry',
 'Fit a statement stream onto cards while reserving label and continuation columns.',
 'Standard F77, inherited from earlier Fortran. Modern fixed form remains available but is obsolescent.',
 'Supported; pin -ffixed-line-length-72. Longer-line options intentionally change the source projection.',
 'Bytes beyond the statement field can carry an independent record channel. A file reader can observe information that compilation ignores.',
 'Combine with formatted records and a generated DATA deck. Architectural role: a two-plane source/state medium. Moving the margin is a machine change, not cosmetic reformatting. [S04,S03,S02]'),
('02','Insignificant blanks and contextual keywords',
 'Make card preparation flexible without reserving every language keyword.',
 'Standard F77 fixed-form lexical behavior; modern fixed form retains it, while free form changes lexical boundaries.',
 'Supported in fixed form. Never infer a token stream merely by splitting on spaces.',
 'A small punctuation edit can change a statement class. Source geometry and token meaning can be experimentally separated.',
 'Combine with column clipping and implicit typing for a compiler-projection exhibit. Good for a differential compiler instrument; poor as hidden production logic. No famous DO typo is needed as the central trick. [S01,S03]'),
('03','D-lines and line-width dialects',
 'Enable or disable diagnostic code without editing the deck.',
 'Vendor practice, not standard F77. Modern standard Fortran does not assign D-lines this meaning.',
 'Documented -fd-lines-as-code and -fd-lines-as-comments; choose explicitly. -std=legacy alone does not identify a DEC or VAX machine.',
 'One physical deck can have several executable projections selected by compiler settings.',
 'Combine with fixed-form margins and a shared specimen corpus. Architectural role: selectable compilation physics with measured phenotype differences. Avoid profiles whose only distinction is a changed banner. [S03]'),
('04','Internal character files',
 'Reuse formatted conversion rules for data already in memory.',
 'Standard F77 sequential formatted internal I/O; modern Fortran retains and extends it.',
 'Supported. Sun internal direct access is a separate extension and is not assumed to work in GNU.',
 'A character array becomes a bounded sequence of records. A READ can reinterpret a line repeatedly through different numeric lenses.',
 'Combine with T positioning, BN/BZ and generated character formats for a record transducer. The original numeric-storage seam was later reduced to CHARACTER under GNU legacy mode; GNU/f95 controls preserve bytes. The revision update specifies that compiler/runtime behavior separately from language semantics. [S05]'),
('05','Runtime character FORMAT',
 'Select an input/output layout after compilation.',
 'Standard F77 character format specifications; retained in modern Fortran.',
 'Supported. Runtime format syntax is parsed by the Fortran runtime rather than by CARBON.',
 'A data record can describe how another record is interpreted or printed. Formats can also print successor formats.',
 'Compose with internal or external records to get a native transducer. This alone is insufficient F77 specificity: modern Fortran already supports it. The selected machine adds numeric-word identity. [S06]'),
('06','FORMAT reversion, slash and colon',
 'Apply compact layouts to long I/O lists and variable amounts of output.',
 'Standard F77; retained. Reversion has a specific parenthesis-based restart point, not an arbitrary branch target.',
 'Supported; exact nested formats should have executable probes.',
 'List exhaustion and nested grouping affect record production; slash advances the record, while colon can end format control when the list is exhausted.',
 'Combine with array records for periodic record tiling or stream framing. Architectural role: sequencing owned by native formatting. The first CARBON specimen stays single-record; multi-record reversion is a proposed extension, not a tested feature of its driver. [S07,S01]'),
('07','T, TL and TR positional editing',
 'Lay out reports and extract fields without making a separate parser.',
 'Standard F77 positional descriptors; retained. Extra vendor tab-stop forms are different features.',
 'Supported; overlapping output was observed in the supplied experiment.',
 'Later transfers can overwrite earlier columns of the same output record. The record is a work surface, not merely an append-only string.',
 'Combine with numeric FORMAT and H literals to repair a printed instruction after a decimal overprint. Architectural role: native spatial rewriting; this is CARBON\'s central actuator. [S08]'),
('08','BN/BZ blank interpretation and P scaling',
 'Read fixed fields and accommodate scientific notation conventions.',
 'Standard F77 BN, BZ and kP; retained. Bare B or P spellings in some manuals can be extensions.',
 'Supported. State the blank and scale modes explicitly in experiments.',
 'The same visible field can denote different numbers under a different lens. Blank positions and decimal placement become active structure.',
 'Combine with repeated READs and fixed-width WRITE for quantized feedback. Architectural role: conversion physics. Scale is not a generic multiplier for every descriptor or every exponent-bearing input. [S09,S10]'),
('09','Output H edit descriptors',
 'Embed a literal output field using a character count instead of quotation delimiters.',
 'H output is standard F77; deleted in Fortran 95. H input is not standard F77. Do not conflate these facts.',
 'Accepted in legacy formats; used by the working specimen.',
 'Literal bodies can contain punctuation that would otherwise be format syntax. A count defines a temporary boundary between grammar and payload.',
 'Combine with T overwriting to stamp a syntax repair into the successor format. Architectural role: a counted literal stencil. This is separate from a Hollerith constant stored in an INTEGER. [S11,S01,S02]'),
('10','Hollerith constants in numeric DATA',
 'Store text before the language had a standard CHARACTER type.',
 'Earlier Fortran practice; F77 Appendix C offers compatibility guidance outside the standard language. Modern standard Fortran uses CHARACTER.',
 'Supported as a legacy extension; DATA KEY/4H1000/ is the prototype\'s representation check.',
 'One declared numeric object contains literal character storage. Word size and byte order become visible.',
 'Combine with A editing and numeric FORMAT to keep text and numeric behavior in one object. Architectural role: representation-dependent initial conditions. Bytes are not portable integers across machines. [S12]'),
('11','Noncharacter arrays as FORMAT',
 'Let old programs retain format text in numeric storage.',
 'Historical compatibility extension, not standard F77 and not a deleted standard feature. Modern standard format expressions are character-based.',
 'Observed under GNU 13.3 legacy mode; isolated -std=f2018 -pedantic-errors probe rejects an INTEGER FORMAT.',
 'An INTEGER array directly supplies the runtime grammar. No source-language cast or custom format interpreter is inserted.',
 'Compose with raw A transfer and record checkpoints. Architectural role: executable data whose declared numeric identity matters. This is the selected opening in the language boundary. [S06; experiment E01]'),
('12','A editing of noncharacter objects',
 'Move Hollerith character fields into and out of numeric words.',
 'Historical compatibility behavior; outside standard F77 CHARACTER A editing and outside modern standard character editing.',
 'Observed for external records and integer A output. Internal A input differs on the measured toolchain; see E03.',
 'A fixed-width field can be absorbed into an integer word without decimal parsing, then emitted either as characters or as its numeric value.',
 'Combine with I10 and noncharacter FORMAT for a representation-to-layout feedback loop. Architectural role: the reversible text/word boundary, conditional on a tested dialect and I/O path. [S13; E01,E03]'),
('13','Sequential unformatted records and markers',
 'Preserve typed values efficiently without decimal text conversion.',
 'Sequential unformatted I/O is standard F77 and retained. Physical markers and subrecord conventions belong to the processor.',
 'Supported. GNU documents leading/trailing markers and possible subrecords; do not infer a universal binary format.',
 'A record can be both a saved machine state and an executable numeric format when reloaded into the same declared objects.',
 'Compose with the plate words for inspectable restart fossils. Architectural role: native checkpoint framing. CARBON verifies 128-byte payloads and the observed four-byte markers; this is a same-profile spool, not portable serialization. [S14]'),
('14','BACKSPACE, REWIND and ENDFILE',
 'Move around a record medium and delimit sequential output.',
 'Standard F77, with earlier tape lineage; retained. Record positioning does not reverse computation.',
 'Supported for suitable sequential files. Direct-access BACKSPACE is not a standard operation.',
 'History can be traversed by records rather than by application-defined byte offsets. File position is observable state.',
 'Combine with unformatted checkpoints for a branchable spool laboratory. Architectural role: temporal navigation. Replaying saved states can undo a session; BACKSPACE cannot invert a lossy transition or supply crash atomicity. [S15]'),
('15','Direct-access REC and RECL',
 'Address disk records without sequential scanning.',
 'Standard F77 direct access; retained. Unformatted RECL units and external representation require processor-specific care.',
 'Supported. Pin the compiler and record-size convention; never assume historical implementations all used byte counts.',
 'Record number and fixed geometry define a storage topology independent of a filesystem directory tree.',
 'Combine with format lenses for a record atlas. Different legal views may inspect the same bytes after controlled close/reopen steps. Architectural role: spatial storage. Overlapping simultaneous connections and undefined unwritten bytes are not a portable trick. [S16]'),
('16','BLOCK DATA as executable initial state',
 'Initialize named COMMON from a separately compiled program unit.',
 'Standard F77, with earlier lineage; obsolescent but retained in modern Fortran.',
 'Supported. An initializer in a static archive needs a verified extraction strategy.',
 'An object file with no ordinary runtime behavior can alter the executable\'s initial world.',
 'Combine with separately compiled state fragments to build an executable/database hybrid. Architectural role: link-time materialization. Only one initializer owns a given named block; competing initializers are not a portable last-writer election. [S17,S02]'),
('17','Archive extraction and unresolved names',
 'Link only the required members of a static library.',
 'Linker behavior, not a FORTRAN language guarantee. Modern object systems still have comparable mechanisms.',
 'Available through the platform linker. Historical g77 EXTERNAL/BLOCK DATA guidance must be re-tested for current gfortran, archive order and LTO.',
 'Presence in an archive and presence in the final executable are different. Symbol demand can select which initial state actually exists.',
 'Compose with BLOCK DATA for RELIQUARY, a world assembled by linkage. Architectural role: topology and reachability before execution. Strong evidence seam, but weaker language exclusivity than CARBON. [S18]'),
('18','COMMON sequences and EQUIVALENCE association',
 'Share storage across program units and reuse scarce memory within them.',
 'Standard F77 forms; obsolescent in modern Fortran. Arbitrary type punning and inconsistent declarations are not all standard-conforming.',
 'Supported; alignment padding is documented and can matter across separate units.',
 'Local names and array shapes can describe a common storage sequence. The declaration map itself becomes inspectable structure.',
 'Combine with static data and a layout viewer for storage tomography. Architectural role: an ABI specimen, not the primary machine-memory idea excluded by the brief. Changing one alias can affect definition status; document exact allowed types. [S20,S19,S02]'),
('19','SAVE and DATA retention',
 'Initialize data and preserve selected state between procedure activations.',
 'Standard F77 SAVE and DATA, retained. Do not equate old physical static storage with a universal retention guarantee for modified DATA locals; use SAVE explicitly.',
 'Supported; allocation switches such as -fno-automatic do not turn stack folklore into language law.',
 'A procedure can carry state without a passed state object. Initial conditions and continuation state are distinct questions.',
 'Combine with ENTRY for a shared segment instrument, or BLOCK DATA for linked initial worlds. Architectural role: scoped persistence during one process. SAVE does not survive process exit. [S21,S22,S19]'),
('20','ENTRY with distinct dummy argument lists',
 'Share a procedure body and local state among several externally named operations.',
 'Standard F77; retained but obsolescent in modern Fortran.',
 'Supported. A dummy absent from the entry actually invoked cannot be treated as a remembered live argument.',
 'One code segment exposes multiple arrival points, with different argument associations and shared saved state.',
 'Combine with SAVE for an instrument whose operations enter different parts of one body. Architectural role: segment topology, not an automatic coroutine or closure. It remains a secondary lens because the brief already explored ENTRY. [S23,S02]'),
('21','Sequence association, adjustable and assumed-size arrays',
 'Let a routine work on caller storage without copying it or receiving a modern descriptor.',
 'Standard F77 forms; retained under modern association rules. Automatic local arrays are not a blanket F77 feature.',
 'Supported; legal extent and type constraints still apply.',
 'A permitted element sequence can be viewed through another dummy shape. Column-major order becomes a geometric operation.',
 'Combine with record slabs or COMMON layouts for tensor/record lenses. Architectural role: shape determined at a call boundary. Out-of-bounds indexing is not a substitute for legal reshaping, and assumed-shape arrays introduce different rules. [S24,S25]'),
('22','Reference-oriented ABI and hidden CHARACTER lengths',
 'Pass large scientific objects cheaply and preserve character lengths across calls.',
 'Argument association is language semantics; exact pointer passing and hidden length placement are compiler ABI conventions. Modern Fortran offers explicit C interoperability.',
 'GNU documents its conventions, including cases involving temporaries and hidden results.',
 'A call has more physical structure than its visible argument list. Link-compatible names alone do not prove ABI compatibility.',
 'Combine with compiler probes and object inspection for an ABI observatory. Architectural role: exposed calling machinery. Conflicting writes through aliased arguments are not legitimized by reference passing. [S25,S26]'),
('23','Implicit typing and statement functions',
 'Reduce declarations and express short local mathematical definitions.',
 'Standard F77. Implicit typing persists; statement functions are obsolescent. IMPLICIT NONE is not a strict F77 feature.',
 'Supported. GNU legacy mode also accepts later constructs, so acceptance is not historical certification.',
 'Names participate in typing; an assignment-shaped line can instead define a small procedure depending on context.',
 'Combine with separate compilation or source projections for a lexical/type experiment. Architectural role: compile-time interpretation. Low value as the main artifact unless the type change visibly transforms behavior and is checked against a conforming case. [S27,S01,S02]'),
('24','Variable FORMAT expressions and ENCODE/DECODE',
 'Compute format parameters dynamically and run formatting against storage before modern internal files.',
 'Vendor extensions, not standard F77. Their roles are largely replaced by character formats and internal I/O.',
 'GNU explicitly lists both as unimplemented; -std=legacy does not enable them.',
 'On supporting implementations, variable expressions can make format evaluation consult program state. ENCODE/DECODE expose a historical memory-facing formatting interface.',
 'Compose with a vendor-specific stencil laboratory. Architectural role: an alternate physics branch with its own compiler requirement. Neither appears silently in the gfortran prototype. [S28,S29]'),
('25','Printer carriage control',
 'Use the first output character to control paper advance and overprinting.',
 'F77-era printing semantics; no universal promise that an ordinary file or modern terminal performs them. Modern facilities and vendor options differ.',
 'GNU documents CARRIAGECONTROL compatibility under DEC I/O options; select explicitly.',
 'A stored record and its physical rendering are different artifacts. Several output records can contribute to one visible printed line.',
 'Combine with a preserved raw spool and a viewer for PAPER TELEGRAPH. Architectural role: an output medium with spatial accumulation. Do not silently treat ANSI terminal escapes or a modern canvas as historical hardware. [S30]'),
('26','Overlays and load/run address separation',
 'Fit mutually exclusive code or data segments into limited memory.',
 'Toolchain/OS architecture, not standard F77. No standard modern Fortran overlay loader is implied.',
 'GNU ld has OVERLAY layout facilities; gfortran alone does not provide the historical manager.',
 'Objects may occupy one runtime address at different times while having distinct load locations.',
 'Compose with surviving COMMON and explicit state spools for an executable whose rooms replace one another. Architectural role: memory/time topology. A Linux prototype must implement or supply the loader; a linker script by itself is insufficient. [S31]'),
('27','List-directed null fields and slash termination',
 'Accept convenient free-form numeric input without explicit field widths.',
 'Standard F77 external list-directed mechanisms; retained. Internal list-directed support has a later history.',
 'Supported. Start with defined destination values before applying null fields.',
 'A null field leaves the associated item unchanged, and slash can terminate the transfer. An input record can therefore act as a sparse state update.',
 'Combine with SAVE or initialized arrays for a stream-driven register garden. Architectural role: patch semantics supplied by the I/O runtime. This is not a complete transaction protocol or a universal NULL value. [S32]'),
('28','Cray pointers and optimizer assumptions',
 'Expose address-based storage and permit aggressive scientific-code optimization.',
 'Cray pointer syntax is a vendor extension; standard modern POINTER is a different facility. Logical evaluation and alias restrictions also constrain old-style programs.',
 'Cray pointers need -fcray-pointer. GNU documents alias limitations and optional elimination of expression calls.',
 'Representation addresses and compiler assumptions become measurable. A working -O0 case can stop working when its source violates those assumptions.',
 'Compose with bounded ABI probes, not the core machine. Architectural role: a laboratory of legal versus accidental behavior. CARBON deliberately needs no pointer forging, overflow, invalid aliasing or short-circuit side effects. [S33,S37,S26]'),
]

CANDIDATES = [
('A','CARBON','A record machine that prints its next executable FORMAT',
 'Numeric FORMAT, Hollerith A transfer, positional overprint and unformatted snapshots form one loop. Printed digits rewrite layout; layout changes raw words; those words feed the next print. A saved record resumes the machine. The working specimen is a four-state oscillator, with no user-defined opcode decoder.',
 'Extension-dependent, intentionally representation-sensitive, and not yet shown to compose into larger useful circuits.',[5,5,4,5,5,5,5,4,5]),
('B','RELIQUARY','A database assembled into existence by the linker',
 'Each carefully scoped BLOCK DATA object contributes an initial-state region. Archive extraction, explicit references and link maps determine which regions are present. Querying the executable reveals the linked world; exporting modified state creates replacement initializer objects for a new executable generation.',
 'Duplicate initialization must be rejected. C and ordinary linkers can reproduce much of the idea, so specificity lies in F77 initialization and storage conventions rather than unique power.',[4,4,5,5,5,4,5,4,4]),
('C','CARD REEF','One deck with a compiled plane and a living margin',
 'Columns in the statement field define a Fortran program; the same physical records carry state outside that field. The program reads and rewrites its own deck, emitting a recompilable successor. Changing source-width physics changes what becomes code, while card ordering and continuation boundaries expose growth seams.',
 'A simple quine or metadata-in-comments demo fails. It earns its place only if compilation and record interpretation disagree productively and reproducibly.',[5,4,4,5,4,4,5,4,5]),
('D','GHOST TYPEWRITER','Input stored inside a FORMAT literal',
 'Recover an earlier implementation where H input overwrites literal material associated with a format. Subsequent output speaks the stored text without an ordinary user variable. Multiple formats would be the storage cells of an interactive inscription instrument. IBM\'s 1965 manual documents the primitive. [S38]',
 'The relevant input behavior is outside F77 and cannot be assumed in gfortran. Needs a verified historical compiler or an explicitly labeled emulator. Fails the immediate prototype gate.',[5,5,4,3,5,1,5,5,4]),
('E','PALINDROME','A branchable history made from native tape records',
 'Every transition emits a complete record-state fossil. Record navigation selects a prior state and forks its future into another spool. The interface lets the user handle time as a tape reel, inspecting the compiler\'s actual framing rather than hiding it behind a database.',
 'This is replay, not mathematically reversible computation. It has a clear capability but is comparatively easy to reproduce in modern file APIs.',[4,3,4,5,5,5,4,3,4]),
('F','OVERLAY WEATHER','An executable with rooms that cannot coexist',
 'Mutually exclusive code regions share one runtime address. A small manager swaps the active room while saved records and deliberate shared storage carry weather between rooms. Object composition and load geometry determine which experiences can follow which.',
 'Loader and operating-system machinery dominate the Linux build. Without real address reuse it collapses into an ordinary plug-in demo.',[5,3,5,4,4,2,5,4,5]),
('G','DECIMAL CLIMATE','A dynamical system whose material is printed precision',
 'Values repeatedly travel through fixed-width numeric formats, blank interpretation and scale settings. Quantization, saturation to asterisks and parse failure become visible phase boundaries. Users alter format plates rather than equations to change the dynamics.',
 'Most mechanisms survive unchanged in modern Fortran. Never depend on undefined results after I/O failure; treat failure as an observed terminal condition.',[4,2,4,5,5,5,4,4,4]),
('H','PAPER TELEGRAPH','A communication medium assembled from overprinted records',
 'Retain every raw carriage-control record and reconstruct the visible page as another state surface. Contributors design signals whose meaning changes when one record is removed, reordered or interpreted by another printer convention. A viewer exposes the divergence between spool and image.',
 'No literal two-way paper memory without an explicit reader. The modern viewer is an emulator of a physical medium, and must say so.',[4,3,4,4,4,4,5,4,4]),
('I','NULL GARDEN','A sparse-update ecosystem driven by missing input fields',
 'Defined register plots receive list-directed records. Values replace cells, null fields preserve them, slash stops a patch, and repetition spreads a value. Multiple saved plots and printed update records create a visibly stateful dataflow garden with almost no parser code.',
 'Useful and small, but modern Fortran retains the native input behavior. It is an excellent secondary specimen and a weaker flagship.',[3,2,3,4,5,5,3,3,3]),
('J','DIALECT ZOO','An executable experiment whose species are compiler profiles',
 'A corpus has controlled alternate interpretations under D-line settings, source widths, word sizes and supported legacy extensions. Each build emits a phenotype record with its toolchain identity and failures. New contributions must add a mechanism, not merely change a constant.',
 'Without individual substantial specimens this is a compiler test suite. It is better as the institution surrounding CARBON than as the first artifact.',[4,4,4,5,3,4,5,5,5]),
]
