      PROGRAM PRESS
C     CARBON / AFTERIMAGE. The pump transports records and supplies a clock.
C     Executable cards choose rules, turns, writes and graph ports.
C     REC= is a host service. No transition arithmetic or IF dispatch here.
      CHARACTER*256 WORLD,HEADS
      CHARACTER*9216 LIBRARY
      CHARACTER*1152 RULES
      CHARACTER*640 COMPASS
      CHARACTER*128 TURNS
      CHARACTER*80 CELL,PATCH
      CHARACTER*64 STAMP
      CHARACTER*32 CODE,NEXT,TURN,HEADING,MOVE,GENOME
      CHARACTER*1 BEFORE,MARK
      INTEGER ROUNDS,COUNT,START,J,K,POS,DEST,HOME,N,E,S,W
      READ(5,'(A)') WORLD
      READ(5,'(A)') HEADS
      READ(5,*) ROUNDS,COUNT,START
      READ(5,'(A9216)') LIBRARY
      READ(5,'(A640)') COMPASS
      OPEN(21,FILE=WORLD,STATUS='OLD',ACCESS='DIRECT',
     +     FORM='FORMATTED',RECL=80)
      OPEN(22,FILE=HEADS,STATUS='OLD',ACCESS='DIRECT',
     +     FORM='FORMATTED',RECL=80)
      DO 20 J=START+1,START+ROUNDS
        DO 10 K=1,COUNT
          READ(22,'(I8:A32:A32:I8)',REC=K)
     +         POS,HEADING,GENOME,HOME
          READ(LIBRARY,GENOME) RULES
          READ(21,'(A80)',REC=POS) CELL
          READ(CELL,'(A32:A1)') CODE,BEFORE
          READ(RULES,CODE) NEXT,TURN,STAMP,MARK
          WRITE(PATCH,STAMP) CELL,NEXT,MARK,HOME
          WRITE(21,'(A80)',REC=POS) PATCH
          READ(COMPASS,HEADING) TURNS,MOVE
          READ(TURNS,TURN) HEADING
          READ(COMPASS,HEADING) TURNS,MOVE
          READ(21,'(A80)',REC=POS) CELL
          READ(CELL,MOVE) DEST
          READ(CELL,'(T41:4I8)') N,E,S,W
          WRITE(22,'(I8:A32:A32:I8)',REC=K)
     +         DEST,HEADING,GENOME,HOME
          WRITE(6,100) J,K,POS,DEST,BEFORE,MARK,HEADING,
     +         NEXT,TURN,STAMP,MOVE,N,E,S,W
   10   CONTINUE
   20 CONTINUE
      CLOSE(21)
      CLOSE(22)
  100 FORMAT(I10,1X,I4,1X,I8,1X,I8,1X,A1,1X,A1,1X,A32,
     +       1X,A32,1X,A32,1X,A64,1X,A32,4(1X,I8))
      END
